import argparse

def makeparse():
    parser = argparse.ArgumentParser("ocr & translate")
    
    parser.add_argument(
        "-r0",
        "--root0",
        type=str,
        default="./pics/example2.jpg",
    )
    parser.add_argument(
        "-r1",
        "--root1",
        type=str,
        default="./pics/example2.jpg",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="./pics/output.jpg",
    )
    parser.add_argument(
        "-tl",
        "--thresh_line",
        type=int,
        default=10,
    )
    parser.add_argument(
        "-tb",
        "--thresh_box",
        type=int,
        default=80,
    )
    parser.add_argument(
        "-e",
        "--extra_size",
        type=int,
        default=20,
    )
    parser.add_argument(
        "-f",
        "--font_size",
        type=int,
        default=35,
    )
    parser.add_argument(
        "--uid",
        type=str,
        default="20220630001260579",
    )
    parser.add_argument(
        "--bkey",
        type=str,
        default="15Yr0dRYfINuQF0w6ptK",
    )
    parser.add_argument(
        "-g",
        "--gpu",
        type=bool,
        default=True,
    )
    parser.add_argument(
        "-rs",
        "--resize",
        type=bool,
        default=True,
    )
    parser.add_argument(
        "-d",
        "--dewarp",
        type=bool,
        default=False,
    )
    parser.add_argument(
        "-m",
        "--model",
        type=int,
        default=0,
    )
    return parser